const artists = {
  artists: {
    name: "Andy Warhol",
    nationality: "American",
  },
};

const artists2 = [
  "Ai Weiwei",
  "Andy Warhol",
  "Auguste Rodin",
  "Banksy",
  "Cai Guo-Qiang 蔡国强",
  "Claude Monet",
  "Da Vinci",
  "David Hockney",
  "El Greco",
  "Elmgreen & Dragset",
  "Georgia O’Keeffe",
  "Jackson Pollock",
  "Jean-Michel Basquiat",
  "Joseph Beuys",
  "KAWS",
  "Lee Bul",
  "Marina Abramović",
  "Mark Rothko",
  "Michael Heizer",
  "Michelangelo Buonarroti",
  "Norman Rockwell",
  "Paul Gauguin",
  "Picasso",
  "Raphael",
  "Richard Serra",
  "Takashi Murakami",
  "Tintoretto",
  "Van Gogh",
  "Wassily Kandinsky",
  "Yayoi Kusama",
  "Yves Klein",
];
